### ISSUE TITLE
Should have non-zero return value for failing specs

### ISSUE THREAD

**Issue by yevgenko** [searls/jasmine-rails#182] opened 2016-01-29 14:08 UTC
When I run the following command on the suite with failing specs, i.e. `failures > 0`:

    bundle exec rake spec:javascript

**Expected:** `echo $?` to NOT be `0`

**Actual result:** `0`

## Workaround

    RAILS_ENV=test be rake spec:javascript

## Source

https://github.com/searls/jasmine-rails/commit/12cc6408c7e4769eb6c62c3e73ff0a2042571136

## Proposal

Perhaps it would be less confusing to stick with one command and update documentation accordingly?

**Comment by pironim** [comment] 2016-01-29 15:05
let me link this issue https://github.com/searls/jasmine-rails/pull/176

**Comment by searls** [comment] 2016-04-07 21:10
I still cannot reproduce the stated problem. Closing until we can get one going.

**Closed by searls** 2016-04-07 21:10 UTC
