### ISSUE TITLE
ERROR: TypeError: 'undefined' is not an object (evaluating 'parent.prototype')

### ISSUE THREAD

**Issue by rbriank** [searls/jasmine-rails#115] opened 2014-04-02 19:07 UTC
Specs all pass if I run a server and browse to /specs

When I run:
```
rake spec:javascript
```
I get:
```
Running `"/usr/local/bin/phantomjs" "/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/gems/jasmine-rails-0.6.0/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "/Users/brian.kierstead/dev/pam/tmp/jasmine/runner.html?spec="`
Running: /Users/brian.kierstead/dev/pam/tmp/jasmine/runner.html?spec=
ERROR: TypeError: 'undefined' is not an object (evaluating 'parent.prototype')
TRACE:
 -> file:///Users/brian.kierstead/dev/pam/tmp/jasmine/assets/pam/mpower.js: 3
 -> file:///Users/brian.kierstead/dev/pam/tmp/jasmine/assets/pam/mpower.js: 6
 -> file:///Users/brian.kierstead/dev/pam/tmp/jasmine/assets/pam/mpower.js: 25
 -> file:///Users/brian.kierstead/dev/pam/tmp/jasmine/assets/pam/mpower.js: 27
rake aborted!
Error executing command: "/usr/local/bin/phantomjs" "/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/gems/jasmine-rails-0.6.0/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "/Users/brian.kierstead/dev/pam/tmp/jasmine/runner.html?spec="
/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/gems/jasmine-rails-0.6.0/lib/jasmine_rails/runner.rb:70:in `run_cmd'
/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/gems/jasmine-rails-0.6.0/lib/jasmine_rails/runner.rb:21:in `block in run'
/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/gems/jasmine-rails-0.6.0/lib/jasmine_rails/runner.rb:48:in `override_rails_config'
/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/gems/jasmine-rails-0.6.0/lib/jasmine_rails/runner.rb:9:in `run'
/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/gems/jasmine-rails-0.6.0/lib/tasks/jasmine-rails_tasks.rake:7:in `block (2 levels) in <top (required)>'
/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/bin/ruby_executable_hooks:15:in `eval'
/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spec:javascript
```

If I run:
```
$ RAILS_ENV=test rake spec:javascript
```
I get:
```
Running `"/usr/local/bin/phantomjs" "/Users/brian.kierstead/.rvm/gems/ruby-2.0.0-p353@pam/gems/jasmine-rails-0.6.0/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "/Users/brian.kierstead/dev/pam/tmp/jasmine/runner.html?spec="`
Running: /Users/brian.kierstead/dev/pam/tmp/jasmine/runner.html?spec=
opening database pam-database in version #18
Notifier: skipping badges while offline.
Starting...
Persist for store values should store
  Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    undefined

  Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    undefined

  TypeError: 'undefined' is not an object (evaluating 'result.key') in file:///Users/brian.kierstead/dev/pam/tmp/jasmine/assets/jasmine-specs.js (line 90489)
    TypeError: 'undefined' is not an object (evaluating 'result.key')
    at file:///Users/brian.kierstead/dev/pam/tmp/jasmine/assets/jasmine-specs.js:90489
    at file:///Users/brian.kierstead/de
......
<snip>
```
In both cases, tmp/jasmine includes all the source files separately and not as a single application.js file.  I'm not sure if that is the problem, but I was reading elsewhere that it could be.

**Comment by tojofo** [comment] 2015-01-06 01:01
@rbriank are you using backbone + marionetter per chance?

**Comment by rbriank** [comment] 2015-01-06 01:29
Only backbone.  Haven't tried this for a while, so it may be working.

**Comment by searls** [comment] 2015-09-19 21:44
Closing unless this is still an issue. Probably caused by peculiarities of production code.

**Closed by searls** 2015-09-19 21:44 UTC
