### ISSUE TITLE
SpecRunner precompiles assets?

### ISSUE THREAD

**Issue by BroiSatse** [searls/jasmine-rails#168] opened 2015-07-29 12:58 UTC
Hi. I am having an issue with SpecRunner loading angular-mocks twice when running tests from the terminal (and this is causing infinite loop). Everything works very nicely when running through the mounted engine though.

In a spec file I have sprocket command `#= require angular-mocks`. When I remove it, I have no access to angular mocks, however when it is there it's causing this file to be loaded twice. After some digging, I managed to find a difference between `runner.html` and `/specs` pages - `runner.html` is using precompiled version of Spec file (with a `angular-mocks` file content included within it) together with `angular-mock` file itself. How can I stop it from doing this?

I have created a simple application to reproduce the issue: https://github.com/BroiSatse/angular-jasmine-error. `localhost:3000/specs` works as charm, `rake spec:javascript` gets an infinite loop.

**Comment by searls** [comment] 2015-08-04 11:03
Try `RAILS_ENV=test rake spec:javascript`. I believe this is a dupe of #121. Could you look at helping finish #162 to resolve this?

**Closed by searls** 2015-08-04 11:03 UTC

**Comment by BroiSatse** [comment] 2015-08-04 11:26
Changing rails environment works. Thank you very much. I'll have a look at #162 in the evening. Again, thanks for help. :+1:
